"""Catálogo de códigos de error — BE-00/BE-01/BE-02."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Códigos mínimos; se amplían en planes posteriores."""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    FORBIDDEN = "FORBIDDEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    WORK_ORDER_NOT_FOUND = "WORK_ORDER_NOT_FOUND"
    WORK_ORDER_ALREADY_STARTED = "WORK_ORDER_ALREADY_STARTED"
    WORK_ORDER_ALREADY_COMPLETED = "WORK_ORDER_ALREADY_COMPLETED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_ALREADY_FINALIZED = "SESSION_ALREADY_FINALIZED"
    STEP_CRITICAL_CANNOT_SKIP = "STEP_CRITICAL_CANNOT_SKIP"
    STEP_REQUIRES_PHOTO = "STEP_REQUIRES_PHOTO"
    PHOTO_NOT_FOUND = "PHOTO_NOT_FOUND"
    PHOTO_VALIDATION_FAILED = "PHOTO_VALIDATION_FAILED"
    MANUAL_INVALID_PDF = "MANUAL_INVALID_PDF"
